[package]
name = "pdfreport"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
printpdf = "*"
tracing = "*"
tracing-subscriber = { version = "*", features = ["std", "fmt"] }
tracing-chrome = "*"
skia-safe = { version = "*", features = ["textlayout"] }
